### ISSUE TITLE
Using two channels simultaneously

### ISSUE THREAD

**Issue by pronvis** [crjeder/hx711_spi#21]
HX711 have two channels: A & B.
Is it possible to connect two measurment devices simultaneously and use your library?

**Comment by crjeder** [comment]
Yes it is possible with the set_mode function, but the maximum sample rate would drop to 1/3. This is because I implemented the mode / chanel change. Per datasheet the mode is changed after the read for the next time. To take effect immediately I added a read.
How would you like to use it?
I am working on the 1.0 version and could easily change the behavior.

**Comment by pronvis** [comment]
Wow, awesome! Could you provide some example of how to use it in that case please?

`How would you like to use it?` I have 4 `DYMH-106` and want one BluePill to get data from them and then send that data via bluetooth to some "motherboard". But bluepill have only 3 SPI interfaces.

**Comment by crjeder** [comment]
Ok. The hx711 is not made to read several load cells. The second channel is meant for e. g. an analog temperature sensor. It is not as sensitive as the first channel. I've added a basic example for using both channels in the documentation / comment of the ```set_mode``` function

**Comment by pronvis** [comment]
Got it, thank you!
Btw, I could not find "basic example for using both channels in the documentation of the 'set_mode'"
